import { FieldMetadataType } from 'src/metadata/field-metadata/field-metadata.entity';

const automationMetadata = {
  nameSingular: 'automation',
  namePlural: 'automations',
  labelSingular: 'Automation',
  labelPlural: 'Automations',
  targetTableName: 'automation',
  description: 'An automation',
  icon: 'IconCheckbox',
  isActive: true,
  isSystem: true,
  fields: [
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.TEXT,
      name: 'name',
      label: 'Name',
      targetColumnMap: {
        value: 'name',
      },
      description: 'Automation name',
      icon: 'IconNotes',
      isNullable: true,
      defaultValue: { value: '' },
    },
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.TEXT,
      name: 'body',
      label: 'Body',
      targetColumnMap: {
        value: 'body',
      },
      description: 'Automation body',
      icon: 'IconList',
      isNullable: true,
      defaultValue: { value: '' },
    },
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.TEXT,
      name: 'type',
      label: 'Type',
      targetColumnMap: {
        value: 'type',
      },
      description: 'Automation type',
      icon: 'IconCheckbox',
      isNullable: false,
      defaultValue: { value: 'Simple' },
    },
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.DATE_TIME,
      name: 'reminderAt',
      label: 'Reminder Date',
      targetColumnMap: {
        value: 'reminderAt',
      },
      description: 'Automation reminder date',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.DATE_TIME,
      name: 'cron',
      label: 'Automation Cron',
      targetColumnMap: {
        value: 'cron',
      },
      description: 'Automation cron timer',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.DATE_TIME,
      name: 'completedAt',
      label: 'Completion Date',
      targetColumnMap: {
        value: 'completedAt',
      },
      description: 'The last time the automation has run',
      icon: 'IconCheck',
      isNullable: true,
    },
    // Relations
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.RELATION,
      name: 'automationTargets',
      label: 'Targets',
      targetColumnMap: {},
      description: 'Automation targets',
      icon: 'IconCheckbox',
      isNullable: true,
    },
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.RELATION,
      name: 'author',
      label: 'Author',
      targetColumnMap: {},
      description:
        'Automation author. This is the person who created the automation',
      icon: 'IconUserCircle',
      isNullable: true,
    },
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.UUID,
      name: 'authorId',
      label: 'Author id (foreign key)',
      targetColumnMap: {},
      description: 'Automation author id foreign key',
      icon: undefined,
      isNullable: false,
      isSystem: true,
    },
  ],
};

export default automationMetadata;
