import { FieldMetadataType } from 'src/metadata/field-metadata/field-metadata.entity';

const automationTargetMetadata = {
  nameSingular: 'automationTarget',
  namePlural: 'automationTargets',
  labelSingular: 'Automation Target',
  labelPlural: 'Automation Targets',
  targetTableName: 'automationTarget',
  description: 'An automation target',
  icon: 'IconCheckbox',
  isActive: true,
  isSystem: true,
  fields: [
    {
      // Relations
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.RELATION,
      name: 'automation',
      label: 'Automation',
      targetColumnMap: {},
      description: 'AutomationTarget automation',
      icon: 'IconCheckbox',
      isNullable: true,
    },
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.RELATION,
      name: 'person',
      label: 'Person',
      targetColumnMap: {},
      description: 'AutomationTarget person',
      icon: 'IconUser',
      isNullable: true,
    },
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.RELATION,
      name: 'company',
      label: 'Company',
      targetColumnMap: {},
      description: 'AutomationTarget company',
      icon: 'IconBuildingSkyscraper',
      isNullable: true,
    },
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.UUID,
      name: 'automationId',
      label: 'Automation id (foreign key)',
      targetColumnMap: {},
      description: 'AutomationTarget automation id foreign key',
      icon: undefined,
      isNullable: false,
      isSystem: true,
      defaultValue: undefined,
    },
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.UUID,
      name: 'personId',
      label: 'Person id (foreign key)',
      targetColumnMap: {},
      description: 'AutomationTarget person id foreign key',
      icon: undefined,
      isNullable: true,
      isSystem: true,
      defaultValue: undefined,
    },
    {
      isCustom: false,
      isActive: true,
      type: FieldMetadataType.UUID,
      name: 'companyId',
      label: 'Company id (foreign key)',
      targetColumnMap: {},
      description: 'AutomationTarget company id foreign key',
      icon: undefined,
      isNullable: true,
      isSystem: true,
      defaultValue: undefined,
    },
  ],
};

export default automationTargetMetadata;
