import { DataSource } from 'typeorm';

import { SeedObjectMetadataIds } from 'src/database/typeorm-seeds/metadata/object-metadata';
import { FieldMetadataType } from 'src/metadata/field-metadata/field-metadata.entity';
import { SeedWorkspaceId } from 'src/database/typeorm-seeds/core/workspaces';

const fieldMetadataTableName = 'fieldMetadata';

export enum SeedAutomationTargetFieldMetadataIds {
  Id = '20202020-27c9-46ba-a744-388ad1544e00',
  CreatedAt = '20202020-d4b0-49c3-9015-53315ff74dc8',
  UpdatedAt = '20202020-dd6d-46bd-bb53-444af7e8ef51',

  Automation = '20202020-2fbc-4f2c-a8f3-6e3fa59b51f0',
  AutomationForeignKey = '20202020-f9c1-4d2c-98bb-104e834d31f3',
  Person = '20202020-1e69-46ed-8015-c02ce2dfb7a1',
  PersonForeignKey = '20202020-ff5d-48a2-8c89-8b206793900d',
  Company = '20202020-ea93-4e0d-94c6-4cc5b8b4ce2a',
  CompanyForeignKey = '20202020-1549-42ef-b0d7-49d9a9ac099a',
}

export const seedAutomationTargetFieldMetadata = async (
  workspaceDataSource: DataSource,
  schemaName: string,
) => {
  await workspaceDataSource
    .createQueryBuilder()
    .insert()
    .into(`${schemaName}.${fieldMetadataTableName}`, [
      'id',
      'objectMetadataId',
      'isCustom',
      'workspaceId',
      'isActive',
      'type',
      'name',
      'label',
      'targetColumnMap',
      'description',
      'icon',
      'isNullable',
      'isSystem',
      'defaultValue',
    ])
    .orIgnore()
    .values([
      // Default fields
      {
        id: SeedAutomationTargetFieldMetadataIds.Id,
        objectMetadataId: SeedObjectMetadataIds.AutomationTarget,
        isCustom: false,
        workspaceId: SeedWorkspaceId,
        isActive: true,
        type: FieldMetadataType.UUID,
        name: 'id',
        label: 'Id',
        targetColumnMap: {
          value: 'id',
        },
        description: undefined,
        icon: undefined,
        isNullable: false,
        isSystem: true,
        defaultValue: { type: 'uuid' },
      },
      {
        id: SeedAutomationTargetFieldMetadataIds.CreatedAt,
        objectMetadataId: SeedObjectMetadataIds.AutomationTarget,
        isCustom: false,
        workspaceId: SeedWorkspaceId,
        isActive: true,
        type: FieldMetadataType.DATE_TIME,
        name: 'createdAt',
        label: 'Creation date',
        targetColumnMap: {
          value: 'createdAt',
        },
        description: undefined,
        icon: 'IconCalendar',
        isNullable: false,
        isSystem: true,
        defaultValue: { type: 'now' },
      },
      {
        id: SeedAutomationTargetFieldMetadataIds.UpdatedAt,
        objectMetadataId: SeedObjectMetadataIds.AutomationTarget,
        isCustom: false,
        workspaceId: SeedWorkspaceId,
        isActive: true,
        type: FieldMetadataType.DATE_TIME,
        name: 'updatedAt',
        label: 'Update date',
        targetColumnMap: {
          value: 'updatedAt',
        },
        description: undefined,
        icon: 'IconCalendar',
        isNullable: false,
        isSystem: true,
        defaultValue: { type: 'now' },
      },
      // Relationships
      {
        id: SeedAutomationTargetFieldMetadataIds.Automation,
        objectMetadataId: SeedObjectMetadataIds.AutomationTarget,
        isCustom: false,
        workspaceId: SeedWorkspaceId,
        isActive: true,
        type: FieldMetadataType.RELATION,
        name: 'automation',
        label: 'Automation',
        targetColumnMap: {},
        description: 'AutomationTarget automation',
        icon: 'IconNotes',
        isNullable: true,
        isSystem: false,
        defaultValue: undefined,
      },
      {
        id: SeedAutomationTargetFieldMetadataIds.AutomationForeignKey,
        objectMetadataId: SeedObjectMetadataIds.AutomationTarget,
        isCustom: false,
        workspaceId: SeedWorkspaceId,
        isActive: true,
        type: FieldMetadataType.UUID,
        name: 'automationId',
        label: 'Automation id (foreign key)',
        targetColumnMap: {},
        description: 'AutomationTarget automation id foreign key',
        icon: undefined,
        isNullable: false,
        isSystem: true,
        defaultValue: undefined,
      },
      {
        id: SeedAutomationTargetFieldMetadataIds.Person,
        objectMetadataId: SeedObjectMetadataIds.AutomationTarget,
        isCustom: false,
        workspaceId: SeedWorkspaceId,
        isActive: true,
        type: FieldMetadataType.RELATION,
        name: 'person',
        label: 'Person',
        targetColumnMap: {},
        description: 'AutomationTarget person',
        icon: 'IconUser',
        isNullable: true,
        isSystem: false,
        defaultValue: undefined,
      },
      {
        id: SeedAutomationTargetFieldMetadataIds.PersonForeignKey,
        objectMetadataId: SeedObjectMetadataIds.AutomationTarget,
        isCustom: false,
        workspaceId: SeedWorkspaceId,
        isActive: true,
        type: FieldMetadataType.UUID,
        name: 'personId',
        label: 'Person id (foreign key)',
        targetColumnMap: {},
        description: 'AutomationTarget person id foreign key',
        icon: undefined,
        isNullable: true,
        isSystem: true,
        defaultValue: undefined,
      },
      {
        id: SeedAutomationTargetFieldMetadataIds.Company,
        objectMetadataId: SeedObjectMetadataIds.AutomationTarget,
        isCustom: false,
        workspaceId: SeedWorkspaceId,
        isActive: true,
        type: FieldMetadataType.RELATION,
        name: 'company',
        label: 'Company',
        targetColumnMap: {},
        description: 'AutomationTarget company',
        icon: 'IconBuildingSkyscraper',
        isNullable: true,
        isSystem: false,
        defaultValue: undefined,
      },
      {
        id: SeedAutomationTargetFieldMetadataIds.CompanyForeignKey,
        objectMetadataId: SeedObjectMetadataIds.AutomationTarget,
        isCustom: false,
        workspaceId: SeedWorkspaceId,
        isActive: true,
        type: FieldMetadataType.UUID,
        name: 'companyId',
        label: 'Company id (foreign key)',
        targetColumnMap: {},
        description: 'AutomationTarget company id foreign key',
        icon: undefined,
        isNullable: true,
        isSystem: true,
        defaultValue: undefined,
      },
    ])
    .execute();
};
